framework:
    messenger:
        failure_transport: failed
        transports:
          async:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              retry_strategy:
                  max_retries: 3
                  multiplier: 2

          failed: 'doctrine://default?queue_name=failed'
        routing:
          'App\Message\CreateNews': async
          'App\Message\CreateNewsComment': async
          'App\Message\CreateNewsImage': async
          'App\Parser\QueueRbc': async
